name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.8'
          channel: 'stable'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet CLI
        run: pip install flet

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses || true

      - name: Build Standalone APK
        run: |
          rm -rf mobile/dist-mobile mobile/build
          flet build apk ./mobile --project "BudgetWise-AI" --flutter-build-args="--debug"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BudgetWise-AI-Android-APK
          path: mobile/build/apk/*.apk